In [1]:
import numpy as np

In [2]:
a1 = [1,2,3,4,5,6,7,8,9,10]

In [3]:
a = np.array(a1)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a.size

10

In [6]:
a.ndim

1

In [7]:
a.dtype

dtype('int32')

In [8]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
a + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
a / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [12]:
b = np.sqrt(a)
b

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [13]:
a[3] #slicing

4

In [14]:
a[7]

8

In [15]:
a[0:3:-1]       #we are traversing from a reverse direction

array([], dtype=int32)

In [16]:
a[: :-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [17]:
#list
l=[
    [1,2,3,4],
    [5,6,7,8],
    [2,3,4,5],
    [3,4,5,5]
]

In [18]:
l1 = np.array(l)
l1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [3, 4, 5, 5]])

In [19]:
l1 = np.array(l,dtype=np.uint8)    #uint8 is used for non-decimal or integer values
l1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [3, 4, 5, 5]], dtype=uint8)

In [20]:
l1 = np.array(l,dtype=np.float16)     #float16 is used for decimal values
l1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [2., 3., 4., 5.],
       [3., 4., 5., 5.]], dtype=float16)

In [21]:
l1**2                             #Square of array -- >> l1

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.],
       [ 4.,  9., 16., 25.],
       [ 9., 16., 25., 25.]], dtype=float16)

In [22]:
l1 + 5               #increment of 5 in each values in the array

array([[ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.],
       [ 7.,  8.,  9., 10.],
       [ 8.,  9., 10., 10.]], dtype=float16)

In [23]:
l1 * l1                 #multiplication of array -->> l1

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.],
       [ 4.,  9., 16., 25.],
       [ 9., 16., 25., 25.]], dtype=float16)

### -------------------------------------------
# Slicing using numpy
### -------------------------------------------


In [24]:
l1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [2., 3., 4., 5.],
       [3., 4., 5., 5.]], dtype=float16)

In [25]:
l1[0:4:2,1:4:2]         #l1(row,column)

array([[2., 4.],
       [3., 5.]], dtype=float16)

In [26]:
l1[0::2]

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]], dtype=float16)

In [27]:
l1[0:2]                #l1(start:end:direction) #l1(row,column)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float16)

In [28]:
l1[1::1]

array([[5., 6., 7., 8.],
       [2., 3., 4., 5.],
       [3., 4., 5., 5.]], dtype=float16)

In [29]:
l1[::,1:4:2]

array([[2., 4.],
       [6., 8.],
       [3., 5.],
       [4., 5.]], dtype=float16)

In [30]:
l1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [2., 3., 4., 5.],
       [3., 4., 5., 5.]], dtype=float16)

In [31]:
l1[1::2,[0,2,3]]

array([[5., 7., 8.],
       [3., 5., 5.]], dtype=float16)

In [32]:
l2 = [ 
        [
            [1,2,3,1,2],
            [4,5,6,4,5],
            [7,8,9,6,5]
        ],
    
        [
            [1,6,4,3,5],
            [4,6,7,1,2],
            [1,5,6,5,6]
        ],
        [
            [6,7,8,5,6],
            [1,3,4,1,5],
            [4,5,6,4,5]
        ],
]

In [33]:
a1 = np.array(l2,dtype=np.uint8)
a1

array([[[1, 2, 3, 1, 2],
        [4, 5, 6, 4, 5],
        [7, 8, 9, 6, 5]],

       [[1, 6, 4, 3, 5],
        [4, 6, 7, 1, 2],
        [1, 5, 6, 5, 6]],

       [[6, 7, 8, 5, 6],
        [1, 3, 4, 1, 5],
        [4, 5, 6, 4, 5]]], dtype=uint8)

In [34]:
a1[0:3:,0:3:2,1:5:2]               #slicing of 3D matrix a1(matrix,row,column)

array([[[2, 1],
        [8, 6]],

       [[6, 3],
        [5, 5]],

       [[7, 5],
        [5, 4]]], dtype=uint8)

In [35]:
l2 = [ 
       [
           [
            [1,2,3,1,2],
            [4,5,6,4,5],
            [7,8,9,6,5]
        ],
    
        [
            [1,6,4,3,5],
            [4,6,7,1,2],
            [1,5,6,5,6]
        ],
        [
            [6,7,8,5,6],
            [1,3,4,1,5],
            [4,5,6,4,5]
        ],
       ]     
]

In [39]:
a2 = np.array(l2,dtype=np.uint8)

In [41]:
a2.shape

(1, 3, 3, 5)

In [43]:
a2.ndim         #Here 4 is showing 4D matrix

4

In [44]:
a2.size

45

In [54]:
table = np.arange(0,50,5)                  #np.arange(first two denotes limits and third one denotes gap)
table += 2                                 #it shows where to start from in the given limits
table

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [55]:
table = np.arange(0,50,5)                  #np.arange(first two denotes limits and third one denotes gap)
table += 5                                #it shows where to start from in the given limits
table

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [56]:
import numpy as np
b = np.arange(-100,0,10)
print(b)

[-100  -90  -80  -70  -60  -50  -40  -30  -20  -10]
